version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8000"  # 8000 konteynerden 8000 host'a yönlendirilir
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
